spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
        - id: passenger-service
          uri: lb://passenger-service
          predicates:
          - Path=/passengers/**

        - id: travel-management-service
          uri: lb://travel-management-service
          predicates:
          - Path=/trips/**,/drivers/**,/routes/**

        - id: location-service
          uri: lb://location-service
          predicates:
          - Path=/location/**

server:
  port: 8080
  error:
    include-message: always # remove when on production

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
